baseURL = "https://emanuelpina.pt/"
languageCode = "en-gb"
title = "Emanuel Pina"
theme = "mytheme"
metaDataFormat = "yaml"
enableRobotsTXT = true
paginatePath = "page"
enableEmoji = true
enableGitInfo = true

[markup]
  [markup.highlight]
    noClasses = false

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[params]
  author = "Emanuel Pina"
  description = "Blog de Emanuel Pina"
  thumbnail = "v1568177166/mugshot_xl.jpg"
  readmore = "Read more"
  paginationpath = "page"
  imagecdn = "https://img.emanuelpina.pt/"
  gitsource = "https://codeberg.org/emanuelpina/emanuelpina.pt/src/branch/"

[permalinks]
  posts = "/:title/"
  categories = "/categories/:title/"
  tags = "/tags/:title/"
